travis:
  secure:
    BINSTAR_TOKEN: VMDcfGPr1HYRCow6AULH/qnnbkjfu/uKFJYjR7OXQyouRZtoHuHgx9K++oIiJpFC2vd+qkJ+pzTU41W3+gB0+hsR4zSUHlM2PA6r2XcdAAeX0sL4B+A0V6C6efdu0IPorcsw36bvYDoK0NT0u97M4pV9+NQ3FE94di8YJG2sOTLTEa8fb74FhPeyaqwwiv7u8m5ft8w1ENF7UGkC1DhdHH5+zWULaPbgeL0bz59jbSGU7u8xF+4ORptFkbAy3UQwVMQ+OUwb2dh4D/rugVbhRcPQ55TvNorM9FfhIvGOVl1WiJsVjHhu4s3pinCIqj1ASNfo8XQNGBS7R+nP6CTwX0NCu0UWLIhC/w6bGM/7IM4qbWwKzlwHL7R31tvaV2ZmjOjTtP0NSalG1v91/iBNSexD2oKqPXcfZFm7BwQb3m4gDx8v+Wv5WiYME63jN0FRVgbcqPOV3B8uvB+1Y95Gh+ndhrD9r6S4i3Gf2JlNvfKHDNlz5qDvQ2dKyjIF/phSIEvOsh/Tcx/+iB6OneqqzuuzIDnvuc2VlMbz0gH/LXOXNj9KtvobVq077aUqcnmomenGl5SiaK0Rmrf5lLzJASaYZPwnlr9E1pIjwlmapFy8+D9vYU2kdP3j7AL/mQNtWmqOqQPRQ1woxkBrbs2R4OGMFX5IfjHlFuYfTyYn15I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
